### ISSUE TITLE
Unable to set clear_cache option

### ISSUE THREAD

**Issue by tegon** [ruby-json-schema/json-schema#225]
Hey guys,
I'm using the gem in my test environment, to validate my api responses, like this:
```ruby
JSON::Validator.validate!("#{ Dir.pwd }/spec/support/api/schemas/product.json", JSON.parse(last_response.body), { strict: true, validate_schema: true })
```

I wanna clear the cache of schemas after each test, so i tried this way
```ruby
JSON::Validator.validate!(schema_path, response.body, { strict: true, validate_schema: true, clear_cache: true })
```
but didn't work

Looking into source code, i was able to make this work by adding this line
```ruby
@validation_options[:clear_cache] = true if @options[:clear_cache] == true
```
below this line: https://github.com/ruby-json-schema/json-schema/blob/master/lib/json-schema/validator.rb#L48

Please let me know if i'm trying to do this wrong.

Thanks.

**Comment by SauloSilva** [comment]
@tegon +1
Am also with the same mistake.
Think this you commented would solve the problem.
