### ISSUE TITLE
JSON API 1.0 Support

### ISSUE THREAD

**Issue by ACPK** [ruby-json-schema/json-schema#272]
Any plans supporting [JSON API 1.0](http://jsonapi.org)?

**Comment by RST-J** [comment]
Supporting in what sense? You mean validating the document structure?
If so, then no. You could write a schema which specifies how a JSON API document has to look like and then validate your actual server response against that schema (assuming it is possible to write a schema for that).

**Comment by jlblcc** [comment]
FYI, there's an existing schema: http://jsonapi.org/faq/#is-there-a-json-schema-describing-json-api.

**Comment by iainbeeston** [comment]
This doesn't make any sense to me. It's like saying we should validate "English poetry" or "Ruby on Rails apps". JSON API is a methodology of defining your json schema. There is no one json schema that can cover all JSON API schemas

**Comment by RST-J** [comment]
So I guess we can close this then.
