### ISSUE TITLE
typeOf array doesn't validate references

### ISSUE THREAD

**Issue by thewatts** [ruby-json-schema/json-schema#281]
#### Payload:
```json
{
  "event": {
    "id": 1,
    "name": "Block Party"
  }
}
```

#### Example Schema:
```json
// base
{
  "type": "object",
  "required": [
    "event"
  ],
  "properties": {
    "event": {
      "typeOf": [
        {"type": "null"},
        {"$ref": "event-simple.json"}
      ]
    }
  }
}
```

```json
// event-simple.json
{
  "type":"object",
  "required":[
    "id",
    "name",
    "starts_at"
  ],
  "properties": {
    "id": { "type": "fixnum" },
    "name": { "type": "string" },
    "starts_at": { "type": "string" }
  }
}
```

The reference `event-simple.json` isn't validated against with the json payload.
(( using strict mode ))

**Comment by thewatts** [comment]
If one of the contribs could give me a quick rundown of how validations happen with the project, I don't mind rolling up my sleeve and debugging / bug fixing / feature adding.

**Comment by iainbeeston** [comment]
I'm a bit confused by what you're doing in your schema, did you mean `allOf` instead of `typeOf`? (So far as I'm aware, `typeOf` isn't a recognised property in json schema)

**Comment by thewatts** [comment]
@iainbeeston -- Hmm... I must have misread something somewhere about staging that an item is either one thing or the other.

Would the correct alternative be to use `oneOf` instead?
```json
{
  "type": "object",
  "required": [
    "event"
  ],
  "properties": {
    "event": {
      "oneOf": [
        {"type": "null"},
        {"$ref": "event-simple.json"}
      ]
    }
  }
}
```

**Comment by iainbeeston** [comment]
But isn't that the same as saying that event is not required? Could you just remove the required property and define the event property as

    "event": { "$ref": "event-simple.json" }

If you need any help with json schema I recommend Understanding JSON Schema

https://spacetelescope.github.io/understanding-json-schema/

**Comment by iainbeeston** [comment]
I'm going to close this for now. If you need any questions about the json schema format itself I recommend checking the json schema Google group

https://groups.google.com/forum/m/#!forum/json-schema

**Comment by thewatts** [comment]
Thanks, @iainbeeston!
I think part of the problem is that I had been validating with strict mode enabled.
