### ISSUE TITLE
Validate a schema

### ISSUE THREAD

**Issue by JurgenJocubeit** [ruby-json-schema/json-schema#287]
How can I just validate a schema against any of the built-in drafts in `/resources`? I don't want to validate any data, just that a schema is valid.

**Comment by iainbeeston** [comment]
Try something like:

    draft_schema = JSON::Validator.validator_for_name("http://json-schema.org/draft-04/schema#")
    JSON::Validator.validate!(draft_schema, your_schema)

**Comment by JurgenJocubeit** [comment]
Excellent, thanks, I'll try that.

**Comment by mchapman17** [comment]
To get this to work I had to use the `metaschema` of the draft schema. So:

```
draft_schema = JSON::Validator.validator_for_name("http://json-schema.org/draft-04/schema#").metaschema
JSON::Validator.validate!(draft_schema, your_schema)
```
