### ISSUE TITLE
NameError: uninitialized constant JSON::Validator::SchemaParseError

### ISSUE THREAD

**Issue by emil-rb** [ruby-json-schema/json-schema#292]
When one passes an object, instead of a valid schema to the library it throws
```
NameError:
       uninitialized constant JSON::Validator::SchemaParseError
```

This seems to be because `SchemaParseError` is under `JSON::Schema`, while the call site is in `JSON::Validator`.

See `lib/json-schema/validator.rb`, line 572 for the call site.

**Comment by iainbeeston** [comment]
Thanks for reporting that, I've just raised a pull request to fix it.

**Comment by emil-rb** [comment]
Thanks for the quick action.
