### ISSUE TITLE
2.7.0 fails validating not required fields

### ISSUE THREAD

**Issue by ktaras** [ruby-json-schema/json-schema#364]
After updating from 2.6.2 to 2.7.0 it fails validating not required fields. For example, I have following scheme:

```
{
  "type": "object",
  "required": ["data"],
  "properties": {
    "data": {
      "type": "object",
      ...
    },
    "included": {
      "type": "array"
    }
  }
}
```
So, as I understand the key `included` shouldn't be required, but when I run tests I get an error:
```
The property '#/' did not contain a required property of 'included'
```

**Comment by iainbeeston** [comment]
Sorry I'm having trouble reproducing that with 2.7.0, can you give me a code example that reproduces the error?

Here's what I'm doing:

```ruby
require "json-schema"

schema = {
  "type" => "object",
  "required" => ["data"],
  "properties" => {
    "data" => {
      "type" => "object"
    },
    "included": {
      "type": "array"
    }
  }
}

JSON::Validator.validate!(schema, { "data" => {} }) # returns true
```

**Comment by ktaras** [comment]
I have `strict: true` and it fails:
```
JSON::Validator.validate!(schema, { "data" => {} }, strict: true)
```

**Comment by iainbeeston** [comment]
Yes, then that's expected behaviour (and it should have been the case in json-schema 2.6.2 as well?).

This is what it says in the readme:

> with the `:strict` option, all properties are condisidered to have `"required": true` and all objects `"additionalProperties": false`

**Comment by ktaras** [comment]
Yes, sorry, my fault. But in 2.6.2 it worked fine, strange thing :)

**Comment by iainbeeston** [comment]
We did fix a lot of bugs in the last release, possibly it was working because of a bug
