### ISSUE TITLE
JSON::Validator.fully_validate(filename, data) fails when trying to parse filename as JSON

### ISSUE THREAD

**Issue by faucct** [ruby-json-schema/json-schema#366]
Hello, I have noticed that this code fails with `JSON::ParserError` though it should have fallen back to reading from file:

```ruby
require 'json'
require 'json-schema'
require 'oj_mimic_json'

JSON::Validator.fully_validate('test.json', {})
```

I have dug deeper and found that the explanation of that.
When I require your gem, it requires  `multi_json` and makes it use its default adapter. This makes it cache `JSON::ParserError` [here](https://github.com/intridea/multi_json/blob/master/lib/multi_json/adapters/json_gem.rb#L8). After that I require `oj_mimic_json` which overrides `JSON::ParserError` [here](https://github.com/ohler55/oj/blob/9087ea97ca7d3760b57edabef1cf87a1459182e9/ext/oj/oj.c#L2058). Now when `JSON.parse` throws an error, [`MultiJSON.load`](https://github.com/intridea/multi_json/blob/master/lib/multi_json.rb#L119) fails to wrap it inside `MultiJSON::ParseError` and as a result you fail to rescue it [here](https://github.com/ruby-json-schema/json-schema/blob/master/lib/json-schema/validator.rb#L418) and don't even try to read the file.
I am not sure which gem is most guilty here, so I will mention this issue there too. The problem can be reproduced without your gem:

```ruby
require 'json'
require 'multi_json'
MultiJson.use nil
require 'oj_mimic_json'

# Throws JSON::ParserError instead of MultiJSON::ParseError
MultiJson.load('test.json')
```

**Comment by RST-J** [comment]
We know that there is a problem with mulit-json. There is a PR ( #339 ) which will remove multi-json.

**Comment by faucct** [comment]
Actually my PR https://github.com/ohler55/oj/pull/320 in `oj` was accepted, so it makes the issue fixed. Closing.
