### ISSUE TITLE
Release 2.8.0 of the gem is missing a tag in the repo

### ISSUE THREAD

**Issue by glennsarti** [ruby-json-schema/json-schema#389]
Release 2.8.0 of the gem is missing a tag in the repo.  I assume it's at commit 20734c1bc388fdc16d53837b2ce9599f21cfa4b7

**Comment by iainbeeston** [comment]
Wow, sorry about that - my bad, I must have forgot to push up tags after the release. I've done it now. FYI your assumption was right - it was 20734c1bc388fdc16d53837b2ce9599f21cfa4b7
