### ISSUE TITLE
:errors_as_objects can never be false in base_schema.validate

### ISSUE THREAD

**Issue by johngluckmdsol** [ruby-json-schema/json-schema#392]
This means that the error message will always contain the UUID of the schema and not the uri.  
That is because 
      [`@base_schema.validate(@data,[],self,@validation_options)`](https://github.com/ruby-json-schema/json-schema/blob/master/lib/json-schema/validator.rb#L115)

uses `@validation_options` and those do not assign `:error_as_objects` so it will always be the default

Note: this is a problem when using `fully_validate`

**Comment by johngluckmdsol** [comment]
Misunderstanding

**Comment by iainbeeston** [comment]
Ok, closing this then
